#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  configure)
    sysctl -p >/dev/null 2>&1 || true
    systemctl daemon-reload >/dev/null 2>&1 || true
    systemctl restart emervpn >/dev/null 2>&1 || true
    systemctl enable emervpn >/dev/null 2>&1 || true
  ;;
esac

exit 0
